name: opgave4

on:
  push:

env:
    APPLICATION_NAME: 'python application'  

jobs:
    
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v2 # checkout the repository content

            - name: setup python  
              uses: actions/setup-python@v1

            - name: install python packages
              run: |
                 python -m pip install --upgrade pip
                 #  pip install --quiet --requirement requirements.txt

            - name: execute py script # run script1.py
              run: python script1.py       

    release:
        name: release
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v1
         
            - name: Upload artifact
              uses: actions/upload-artifact@v1
              with: 
                name: script
                path: ..
       
   
