FROM openjdk:11-jdk
ADD app /app
WORKDIR /app
RUN javac -cp lombok.jar Forever.java
RUN rm Forever.java
RUN if [ -f ./Forever.java ]; then \
        echo "File exists!"; \
    else \
        echo "File does not exist!"; \
    fi
CMD ["java", "Forever", "-cp", "lombok.jar"]
